server:
  port: 8889

springdoc:
  swagger-ui:
    config-url: /v3/api-docs/swagger-config
    urls:
      - name: reviews-service
        url: /reviews/v3/api-docs
      - name: flatbuddy-service
        url: /users/v3/api-docs
      - name: reports-service
        url: /reports/v3/api-docs
      - name: favorites-service
        url: /favorites/v3/api-docs
      - name: flat-listing-service
        url: /api-docs.json
        #/flats/api-docs.json
      

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: reviews-swagger
          uri: http://flat-listing-service:3000
          predicates:
           - Path=/api-docs.json

        - id: reviews-swagger
          uri: http://reviews-service:9001
          predicates:
           - Path=/reviews/v3/api-docs
          filters:
           - RewritePath=/reviews/v3/api-docs, /v3/api-docs
           
        - id: reports-swagger
          uri: http://reports-service:8081
          predicates:
           - Path=/reports/v3/api-docs
          filters:
           - RewritePath=/reports/v3/api-docs, /v3/api-docs
           
        - id: reports-route
          uri: http://reports-service:8081
          predicates:
           - Path=/reports/**
           
        - id: reviews-route
          uri: http://reviews-service:9001
          predicates:
            - Path=/reviews/**
#          filters:
#            - RewritePath=/reviews/(?<path>.*), /$\{path}       
            
        - id: favorites-swagger
          uri: http://favorites-service:9000
          predicates:
            - Path=/favorites/v3/api-docs
          filters:
            - RewritePath=/favorites/v3/api-docs, /v3/api-docs
            
        - id: favorites-route
          uri: http://favorites-service:9000
          predicates:
            - Path=/favorites/**
#          filters:
#            - RewritePath=/favorites/(?<path>.*), /$\{path}

        - id: flatbuddy-swagger
          uri: http://flatbuddy-service:8080
          predicates:
            - Path=/users/v3/api-docs
          filters:
            - RewritePath=/users/v3/api-docs, /v3/api-docs
            
        - id: flatbuddy-route
          uri: http://flatbuddy-service:8080
          predicates:
            - Path=/users/**
#          filters:
#            - RewritePath=/favorites/(?<path>.*), /$\{path}
            
        - id: flat-listing-service-route1
          uri: http://flat-listing-service:3000
          predicates:
            - Path=/flats/**
#          filters:
#            - RewritePath=/flats/(?<path>.*), /$\{path}
            
        - id: flat-listing-service
          uri: http://flat-listing-service:3000
          predicates:
            - Path=/api/users/**
#          filters:
#            - RewritePath=/api/users/(?<path>.*), /$\{path}

        

      default-filters:
        - AddRequestHeader=X-Request-Gateway, Gateway-Service



