apiVersion: v1
kind: Service
metadata:
  name: gateway-router
spec:
  type: NodePort
  selector:
    app: gateway-router
  ports:
    - protocol: TCP
      port: 8889
      targetPort: 8889
      nodePort: 38889
